FROM node:18-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm config set registry https://registry.npmmirror.com && npm ci --no-audit --no-fund
COPY . .
EXPOSE 18040
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
